{{- if .Values.ldap.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "redstone.fullname" . }}-ldap
  labels:
    {{- include "redstone.labels" . | nindent 4 }}
    app.kubernetes.io/component: ldap
spec:
  replicas: {{ .Values.ldap.replicaCount }}
  selector:
    matchLabels:
      {{- include "redstone.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: ldap
  template:
    metadata:
      labels:
        {{- include "redstone.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: ldap
        service: ldap
        component: authentication
    spec:
      containers:
        - name: ldap
          image: "{{ .Values.ldap.image.repository }}:{{ .Values.ldap.image.tag }}"
          imagePullPolicy: {{ .Values.ldap.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.ldap.service.targetPort }}
              protocol: TCP
            - name: ldap
              containerPort: 3890
              protocol: TCP
          env:
            {{- toYaml .Values.ldap.env | nindent 12 }}
          resources:
            {{- toYaml .Values.ldap.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
          volumeMounts:
            - name: ldap-data
              mountPath: /data
      volumes:
        - name: ldap-data
          persistentVolumeClaim:
            claimName: {{ include "redstone.fullname" . }}-ldap-data
{{- end }}
---
{{- if .Values.ldap.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "redstone.fullname" . }}-ldap
  labels:
    {{- include "redstone.labels" . | nindent 4 }}
    app.kubernetes.io/component: ldap
spec:
  type: {{ .Values.ldap.service.type }}
  ports:
    - port: {{ .Values.ldap.service.port }}
      targetPort: {{ .Values.ldap.service.targetPort }}
      protocol: TCP
      name: http
    - port: 3890
      targetPort: 3890
      protocol: TCP
      name: ldap
  selector:
    {{- include "redstone.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ldap
{{- end }}
---
{{- if .Values.ldap.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "redstone.fullname" . }}-ldap-data
  labels:
    {{- include "redstone.labels" . | nindent 4 }}
    app.kubernetes.io/component: ldap
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  {{- if .Values.global.storageClass }}
  storageClassName: {{ .Values.global.storageClass }}
  {{- end }}
{{- end }}
