# Redstone Release.com Configuration
# Following the "Built for Clarity" design philosophy
# Using Helm chart deployment instead of docker-compose for better logging

# Helm configuration
helm:
  chart: ./helm/redstone
  valuesFiles:
    - ./helm/redstone/values.yaml
  # Ensure Helm dependencies are updated before deployment
  dependencyUpdate: true

# Build configuration
build:
  timeout: 1800  # 30 minutes, for larger builds
  # Use pre-built images from Helm chart values
  skipBuild: true
  
# Deployment strategy
deployment:
  strategy: helm
  namespace: redstone
  createNamespace: true

# Static Environment Configuration with Git Tag-Based Deployments
environments:
  # Development - continuous deployment from main branch
  development:
    branch: main
    autoDeployment: true
    persistence: true  # Static environment - doesn't get destroyed
    helm:
      values:
        redmica:
          replicaCount: 1
          image:
            repository: redmica/redmica
            tag: "3.1.0"
            pullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 512Mi
        postgresqlCustom:
          primary:
            resources:
              limits:
                cpu: 500m
                memory: 1Gi
              requests:
                cpu: 250m
                memory: 512Mi
        ldap:
          replicaCount: 1
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
        prometheus:
          server:
            resources:
              limits:
                cpu: 300m
                memory: 512Mi
              requests:
                cpu: 150m
                memory: 256Mi
        grafana:
          resources:
            limits:
              cpu: 300m
              memory: 512Mi
            requests:
              cpu: 150m
              memory: 256Mi
          ingress:
            enabled: true
            hosts:
              - host: dev-grafana.redstone.example.com
                paths:
                  - path: /
                    pathType: Prefix
        # Enable logging stack
        loki:
          enabled: true
        logging:
          fluentBit:
            enabled: true
    domains:
      - dev.redstone.example.com
      - dev-grafana.redstone.example.com

  # Staging - deploys from release candidate tags (v*-rc.*)
  staging:
    tags: "v*-rc.*"  # e.g., v1.2.0-rc.1, v1.2.0-rc.2
    autoDeployment: false  # Requires manual approval
    persistence: true  # Static environment - doesn't get destroyed
    helm:
      values:
        redmica:
          replicaCount: 1
          image:
            repository: redmica/redmica
            tag: "3.1.0"
            pullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 1500m
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 1Gi
        postgresqlCustom:
          primary:
            resources:
              limits:
                cpu: 800m
                memory: 1500Mi
              requests:
                cpu: 400m
                memory: 750Mi
        ldap:
          replicaCount: 1
          resources:
            limits:
              cpu: 300m
              memory: 384Mi
            requests:
              cpu: 150m
              memory: 192Mi
        prometheus:
          server:
            resources:
              limits:
                cpu: 500m
                memory: 768Mi
              requests:
                cpu: 250m
                memory: 384Mi
        grafana:
          resources:
            limits:
              cpu: 400m
              memory: 768Mi
            requests:
              cpu: 200m
              memory: 384Mi
          ingress:
            enabled: true
            hosts:
              - host: staging-grafana.redstone.example.com
                paths:
                  - path: /
                    pathType: Prefix
        # Enable logging stack
        loki:
          enabled: true
        logging:
          fluentBit:
            enabled: true
    domains:
      - staging.redstone.example.com
      - staging-grafana.redstone.example.com

  # Production - deploys from stable release tags (v* excluding -rc)
  production:
    tags: "v*"
    exclude_tags: "v*-rc.*"  # Exclude release candidates
    autoDeployment: false  # Always requires manual approval
    persistence: true  # Static environment - doesn't get destroyed
    helm:
      values:
        redmica:
          replicaCount: 2
          image:
            repository: redmica/redmica
            tag: "3.1.0"
            pullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 2000m
              memory: 2Gi
            requests:
              cpu: 1000m
              memory: 1Gi
        postgresqlCustom:
          primary:
            resources:
              limits:
                cpu: 1000m
                memory: 2Gi
              requests:
                cpu: 500m
                memory: 1Gi
        ldap:
          replicaCount: 2
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
        prometheus:
          server:
            resources:
              limits:
                cpu: 1000m
                memory: 1Gi
              requests:
                cpu: 500m
                memory: 512Mi
        grafana:
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 512Mi
          ingress:
            enabled: true
            hosts:
              - host: grafana.redstone.example.com
                paths:
                  - path: /
                    pathType: Prefix
        # Enable logging stack
        loki:
          enabled: true
        logging:
          fluentBit:
            enabled: true
    domains:
      - redstone.example.com
      - grafana.redstone.example.com

# Health check configuration for Helm deployments
healthChecks:
  redmica:
    path: /
    port: 3000
  postgresql:
    port: 5432
    tcp: true
  ldap:
    port: 3890
    tcp: true
  prometheus:
    path: /-/healthy
    port: 9090
  grafana:
    path: /api/health
    port: 3000
  loki:
    path: /ready
    port: 3100

# Data persistence configuration
persistence:
  postgres:
    size: 10Gi
    storageClass: "standard"
  redmica:
    size: 5Gi
    storageClass: "standard"
  ldap:
    size: 1Gi
    storageClass: "standard"
  prometheus:
    size: 5Gi
    storageClass: "standard"
  grafana:
    size: 1Gi
    storageClass: "standard"

# Custom domain configuration
domains:
  production:
    - domain: redstone.example.com
      service: redmica
    - domain: grafana.redstone.example.com
      service: grafana
    - domain: prometheus.redstone.example.com
      service: prometheus