# Redstone Release.com Application Template
# Following the "Built for Clarity" design philosophy

# Release.com application configuration template
application:
  name: redstone
  description: A modular, cloud-native Redmica deployment with monitoring and LDAP authentication

# Reference to the main docker compose configuration
dockerCompose: ./docker-compose.yml

# Environment variables that can be overridden per environment
environmentVariables:
  # PostgreSQL configuration
  - name: POSTGRES_USER
    description: PostgreSQL database username
    required: true
    defaultValue: postgres
    
  - name: POSTGRES_PASSWORD
    description: PostgreSQL database password
    required: true
    secret: true
    
  - name: POSTGRES_DB
    description: PostgreSQL database name
    required: true
    defaultValue: redmica
    
  # Redmica configuration
  - name: REDMINE_DB_POSTGRES
    description: PostgreSQL database hostname
    required: true
    defaultValue: postgres
    
  - name: REDMINE_DB_DATABASE
    description: Redmica database name
    required: true
    defaultValue: redmica
    
  - name: REDMINE_DB_USERNAME
    description: Redmica database username
    required: true
    defaultValue: postgres
    
  - name: REDMINE_DB_PASSWORD
    description: Redmica database password
    required: true
    secret: true
    
  - name: REDMINE_SECRET_KEY_BASE
    description: Secret key base for Rails
    required: true
    secret: true
    
  # LDAP configuration
  - name: LDAP_DOMAIN
    description: LDAP domain
    required: true
    defaultValue: redstone.local
    
  - name: LDAP_ORGANISATION
    description: LDAP organization name
    required: true
    defaultValue: Redstone Project
    
  - name: LDAP_ADMIN_PASSWORD
    description: LDAP admin password
    required: true
    secret: true
    defaultValue: admin
    
  - name: LDAP_CONFIG_PASSWORD
    description: LDAP config password
    required: true
    secret: true
    defaultValue: config
    
  # Monitoring configuration
  - name: GF_SECURITY_ADMIN_USER
    description: Grafana admin username
    required: true
    defaultValue: admin
    
  - name: GF_SECURITY_ADMIN_PASSWORD
    description: Grafana admin password
    required: true
    secret: true
    defaultValue: admin
    
# Resource limits for services
resources:
  redmica:
    cpu: 1000m
    memory: 1Gi
    
  postgres:
    cpu: 500m
    memory: 1Gi
    
  ldap:
    cpu: 200m
    memory: 256Mi
    
  grafana:
    cpu: 300m
    memory: 512Mi
    
  prometheus:
    cpu: 300m
    memory: 512Mi
    
# Data persistence configuration
persistence:
  postgres:
    size: 10Gi
    
  redmica:
    size: 5Gi
    
  ldap:
    size: 1Gi
    
  prometheus:
    size: 5Gi
    
  grafana:
    size: 1Gi
    
# Health checks for each service
healthChecks:
  redmica:
    path: /
    port: 3000
    initialDelaySeconds: 60
    periodSeconds: 20
    
  postgres:
    port: 5432
    protocol: tcp
    periodSeconds: 15
    
  ldap:
    port: 389
    protocol: tcp
    periodSeconds: 15
    
  prometheus:
    path: /-/healthy
    port: 9090
    periodSeconds: 20
    
  grafana:
    path: /api/health
    port: 3001
    periodSeconds: 20
