version: "3.8"

services:
  # PostgreSQL database for Redmica
  postgres:
    image: postgres:${POSTGRES_VERSION:-15}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_USER: postgres
      POSTGRES_DB: redmica_production
    volumes:
      - ./storage/postgres:/var/lib/postgresql/data
      - ./components/postgres/config:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - redstone-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redmica - Redmine fork for project management
  redmica:
    image: redmica/redmica:${REDMICA_VERSION:-3.1.7}
    environment:
      REDMINE_DB_POSTGRES: postgres
      REDMINE_DB_USERNAME: postgres
      REDMINE_DB_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      SECRET_KEY_BASE: ${REDMICA_SECRET_KEY_BASE:-changemeinproduction}
      REDMINE_PLUGINS_MIGRATE: 'true'
    volumes:
      - ./storage/redmica/files:/usr/src/redmine/files
      - ./storage/redmica/plugins:/usr/src/redmine/plugins
      - ./components/redmica/config:/usr/src/redmine/config/configuration.yml.d
    ports:
      - "${REDMICA_PORT:-3000}:3000"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - redstone-network

  # LDAP service for authentication
  ldap:
    image: osixia/openldap:1.5.0
    command: --copy-service
    volumes:
      - ./storage/ldap/data:/var/lib/ldap
      - ./storage/ldap/config:/etc/ldap/slapd.d
      - ./components/ldap/config/users.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/users.ldif
    environment:
      - LDAP_ORGANISATION=Redstone Project
      - LDAP_DOMAIN=redstone.local
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD:-admin}
      - LDAP_CONFIG_PASSWORD=${LDAP_CONFIG_PASSWORD:-config}
      - LDAP_TLS=false
      - LDAP_READONLY_USER=false
      - LDAP_REPLICATION=false
      - KEEP_EXISTING_CONFIG=false
      - LDAP_REMOVE_CONFIG_AFTER_SETUP=true
      - BOOTSTRAP=true
    ports:
      - "389:389"
      - "636:636"
    networks:
      - redstone-network
    restart: unless-stopped

  # Monitoring - Grafana
  grafana:
    image: grafana/grafana:${GRAFANA_VERSION:-9.5.2}
    volumes:
      - ./storage/grafana:/var/lib/grafana
      - ./components/monitoring/grafana:/etc/grafana/provisioning
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD:-admin}
      GF_USERS_ALLOW_SIGN_UP: "false"
    ports:
      - "${GRAFANA_PORT:-3001}:3000"
    networks:
      - redstone-network
    restart: unless-stopped
    depends_on:
      - prometheus

  # Monitoring - Prometheus
  prometheus:
    image: prom/prometheus:${PROMETHEUS_VERSION:-v2.44.0}
    volumes:
      - ./storage/prometheus:/prometheus
      - ./components/monitoring/prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - "${PROMETHEUS_PORT:-9090}:9090"
    networks:
      - redstone-network
    restart: unless-stopped

  # Frontend - Nginx reverse proxy
  frontend:
    image: nginx:${NGINX_VERSION:-1.25-alpine}
    volumes:
      - ./components/frontend/config/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${FRONTEND_PORT:-8080}:80"
    depends_on:
      - redmica
      - api
      - grafana
      - prometheus
    networks:
      - redstone-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # API Service - Flask application
  api:
    build:
      context: ./components/api
      dockerfile: Dockerfile
    environment:
      - DEBUG=${API_DEBUG:-false}
      - API_SECRET_KEY=${API_SECRET_KEY:-dev-secret-key}
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD:-postgres}@postgres:5432/redmica_production
      - REDIS_URL=redis://redis:6379/0
      - ENVIRONMENT=${ENVIRONMENT:-development}
    volumes:
      - ./components/api/config:/app
    ports:
      - "${API_PORT:-8080}:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - redstone-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Background Worker Service
  worker:
    build:
      context: ./components/worker
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - WORKER_ID=${WORKER_ID:-worker-1}
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD:-postgres}@postgres:5432/redmica_production
    volumes:
      - ./components/worker/config:/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - redstone-network
    restart: unless-stopped
    deploy:
      replicas: ${WORKER_REPLICAS:-1}

  # Redis - Cache and message queue
  redis:
    image: redis:${REDIS_VERSION:-7-alpine}
    volumes:
      - ./storage/redis:/data
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - redstone-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: redis-server --appendonly yes

networks:
  redstone-network:
    driver: bridge

# No longer need named volumes since we're using local directories for persistence