---
# Default Redmica configuration
trackers:
  - name: Bug
    default: true
    description: Software defect that needs to be fixed
  - name: Feature
    default: false
    description: New functionality to be implemented
  - name: Support
    default: false
    description: Support or assistance request

statuses:
  - name: New
    default: true
  - name: In Progress
    default: false
  - name: Resolved
    default: false
  - name: Feedback
    default: false
  - name: Closed
    default: false
  - name: Rejected
    default: false
