production:
  # LDAP authentication configuration for lldap
  ldap:
    enabled: true
    host: ldap
    port: 389
    account: 'uid=admin,cn=users,dc=redstone,dc=local'
    password: '${LDAP_ADMIN_PASSWORD:-adminadmin}'
    base_dn: 'cn=users,dc=redstone,dc=local'
    attr_login: uid
    attr_firstname: givenName
    attr_lastname: sn
    attr_mail: mail
    attr_username: displayName
    # Group settings - enables sync from LDAP groups to Redmica groups
    group_base_dn: 'cn=groups,dc=redstone,dc=local'
    group_scope: sub
    group_filter: ''
    group_attribute: cn
    member_attribute: member
    # On-the-fly user creation settings
    onthefly_register: true
    # Only allow LDAP authentication - set to false if you need local admin accounts
    tls: false
    timeout: 20
