# Redstone Release.com Application Template
# Following the "Built for Clarity" design philosophy

# Release.com application configuration template
application:
  name: redstone
  description: A modular, cloud-native Redmica deployment with monitoring and LDAP authentication

# Reference to the main docker compose configuration
dockerCompose: ./docker-compose.yml

# Resource limits for services
resources:
  redmica:
    cpu: 1000m
    memory: 1Gi
    
  postgres:
    cpu: 500m
    memory: 1Gi
    
  ldap:
    cpu: 200m
    memory: 256Mi
    
  grafana:
    cpu: 300m
    memory: 512Mi
    
  prometheus:
    cpu: 300m
    memory: 512Mi
    
# Data persistence configuration
persistence:
  postgres:
    size: 10Gi
    
  redmica:
    size: 5Gi
    
  ldap:
    size: 1Gi
    
  prometheus:
    size: 5Gi
    
  grafana:
    size: 1Gi
    
# Health checks for each service
healthChecks:
  redmica:
    path: /
    port: 3000
    initialDelaySeconds: 60
    periodSeconds: 20
    
  postgres:
    port: 5432
    protocol: tcp
    periodSeconds: 15
    
  ldap:
    port: 389
    protocol: tcp
    periodSeconds: 15
    
  prometheus:
    path: /-/healthy
    port: 9090
    periodSeconds: 20
    
  grafana:
    path: /api/health
    port: 3001
    periodSeconds: 20
