---
execution_type: server
context: release-customer-us-west-2
domain: rls.sh
repo_name: zacharyelston/redstone
tracking_branch: main

environment_templates:
  - name: production
  - name: staging

resources:
  cpu:
    requests: 500m
    limits: 1000m
  memory:
    requests: 512Mi
    limits: 2Gi
  replicas: 1

charts:
  - directory: helm/redstone
    name: redstone
    values: values.yaml

workflows:
  - name: setup
    parallelize:
      - step: charts
        tasks:
          - charts.redstone
  - name: patch
    parallelize:
      - step: charts
        tasks:
          - charts.redstone
  - name: teardown
    parallelize:
      - step: remove-environment
        tasks:
          - release.remove_environment

