# Redstone Environment Template for Release.com
# Following the "Built for Clarity" design philosophy

environment:
  name: ${ENVIRONMENT_NAME}
  type: ${ENVIRONMENT_TYPE}
  description: ${ENVIRONMENT_DESCRIPTION}

# Environment variable mappings from Release.com
mapping:
  COMMIT_HASH: RELEASE_COMMIT_SHA
  CLUSTER_REGION: RELEASE_CLUSTER_REGION
  NAMESPACE: RELEASE_NAMESPACE

# Default environment variables for all services
defaults:
  - key: RAILS_ENV
    value: production
  - key: REDMINE_DB_HOSTNAME
    value: redstone-postgresql
  - key: REDMINE_DB_DATABASE
    value: ${REDMINE_DB_DATABASE}
  - key: LDAP_HOST
    value: redstone-lldap
  - key: LDAP_PORT
    value: "3890"

# Service-specific environment variables
services:
  redmica:
    - key: REDMINE_DB_USERNAME
      value: ${REDMINE_DB_USERNAME}
    - key: REDMINE_DB_PASSWORD
      secret: true
    - key: REDMINE_SECRET_KEY_BASE
      secret: true
    - key: REDMINE_LDAP_HOST
      value: redstone-lldap
    - key: REDMINE_LDAP_PORT
      value: "3890"
      
  postgres:
    - key: POSTGRES_DB
      value: ${REDMINE_DB_DATABASE}
    - key: POSTGRES_USER
      value: ${REDMINE_DB_USERNAME}
    - key: POSTGRES_PASSWORD
      secret: true
      
  ldap:
    - key: LLDAP_JWT_SECRET
      secret: true
    - key: LLDAP_LDAP_USER_PASS
      secret: true
    - key: LLDAP_LDAP_BASE_DN
      value: "dc=redstone,dc=local"
      
  grafana:
    - key: GF_SECURITY_ADMIN_USER
      value: ${GF_ADMIN_USER}
    - key: GF_SECURITY_ADMIN_PASSWORD
      secret: true

# Helm values configuration
helm:
  values:
    # Global configuration
    global:
      domain: ${DOMAIN}
    
    redmica:
      replicaCount: ${REDMICA_REPLICAS:-1}
      image:
        repository: redmica/redmica
        tag: "3.1.0"
        pullPolicy: IfNotPresent
      # Environment variables will be injected by Release.com
      # based on the services configuration above
    
    postgresqlCustom:
      enabled: true
      auth:
        postgresPassword: ${POSTGRES_PASSWORD:-redstone123}
        username: ${REDMINE_DB_USERNAME:-redmica}
        password: ${POSTGRES_PASSWORD:-redmica123}
        database: ${REDMINE_DB_DATABASE:-redmica}
      primary:
        persistence:
          enabled: true
          size: ${POSTGRES_STORAGE_SIZE:-8Gi}
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
    
    ldap:
      enabled: true
      image:
        repository: lldap/lldap
        tag: "latest"
        pullPolicy: IfNotPresent
      replicaCount: 1
      service:
        type: ClusterIP
        port: 3890
        targetPort: 3890
      env:
        - name: LLDAP_LDAP_PORT
          value: "3890"
        - name: LLDAP_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: redstone-secrets
              key: ldap-jwt-secret
        - name: LLDAP_LDAP_USER_PASS
          valueFrom:
            secretKeyRef:
              name: redstone-secrets
              key: ldap-admin-password
      resources:
        limits:
          cpu: 200m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 128Mi
    
    grafana:
      enabled: true
      adminPassword: ${GF_ADMIN_PASSWORD:-admin123}
      service:
        type: ClusterIP
        port: 3000
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
          - ${GRAFANA_HOST:-grafana.local}
        path: /
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 250m
          memory: 256Mi
      persistence:
        enabled: true
        size: ${GRAFANA_STORAGE_SIZE:-2Gi}
    
    prometheus:
      enabled: true
      server:
        persistentVolume:
          enabled: true
          size: ${PROMETHEUS_STORAGE_SIZE:-8Gi}
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
      alertmanager:
        enabled: false
      pushgateway:
        enabled: false
      nodeExporter:
        enabled: true
    
    loki:
      enabled: true
      singleBinary:
        replicas: 1
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
        persistence:
          enabled: true
          size: 10Gi
    
    logging:
      fluentBit:
        enabled: true

# Secret configurations for Helm deployment
secrets:
  redstone-secrets:
    - name: secret-key-base
      value: ${REDMINE_SECRET_KEY_BASE}
    - name: ldap-jwt-secret
      value: ${LDAP_JWT_SECRET}
    - name: ldap-admin-password
      value: ${LDAP_ADMIN_PASSWORD}
