# Redstone Environment Template for Release.com
# Following the "Built for Clarity" design philosophy

environment:
  name: ${ENVIRONMENT_NAME}
  type: ${ENVIRONMENT_TYPE}
  description: ${ENVIRONMENT_DESCRIPTION}

# Service configuration
services:
  redmica:
    replicas: ${REDMICA_REPLICAS:-1}
    image: redmine:5.0.5
    env:
      - name: REDMINE_DB_POSTGRES
        value: postgres
      - name: REDMINE_DB_DATABASE
        value: ${REDMINE_DB_DATABASE:-redmica}
      - name: REDMINE_DB_USERNAME
        value: ${REDMINE_DB_USERNAME:-postgres}
      - name: REDMINE_DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: postgres-credentials
            key: password
      - name: REDMINE_SECRET_KEY_BASE
        valueFrom:
          secretKeyRef:
            name: redmica-secrets
            key: secret-key-base
    ingress:
      enabled: true
      host: ${REDMICA_HOST}
      tls: true
      
  postgres:
    replicas: 1
    image: postgres:15
    env:
      - name: POSTGRES_USER
        value: ${POSTGRES_USER:-postgres}
      - name: POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
            name: postgres-credentials
            key: password
      - name: POSTGRES_DB
        value: ${POSTGRES_DB:-redmica}
    persistence:
      enabled: true
      storageClass: ${STORAGE_CLASS:-standard}
      size: ${POSTGRES_STORAGE_SIZE:-10Gi}
      
  ldap:
    replicas: 1
    image: osixia/openldap:1.5.0
    env:
      - name: LDAP_DOMAIN
        value: ${LDAP_DOMAIN:-redstone.local}
      - name: LDAP_ORGANISATION
        value: ${LDAP_ORGANISATION:-Redstone Project}
      - name: LDAP_ADMIN_PASSWORD
        valueFrom:
          secretKeyRef:
            name: ldap-credentials
            key: admin-password
      - name: LDAP_CONFIG_PASSWORD
        valueFrom:
          secretKeyRef:
            name: ldap-credentials
            key: config-password
      - name: LDAP_TLS
        value: "false"
    persistence:
      enabled: true
      storageClass: ${STORAGE_CLASS:-standard}
      size: ${LDAP_STORAGE_SIZE:-1Gi}
      
  grafana:
    replicas: 1
    image: grafana/grafana:latest
    env:
      - name: GF_SECURITY_ADMIN_USER
        value: ${GF_ADMIN_USER:-admin}
      - name: GF_SECURITY_ADMIN_PASSWORD
        valueFrom:
          secretKeyRef:
            name: grafana-credentials
            key: admin-password
      - name: GF_USERS_ALLOW_SIGN_UP
        value: "false"
      - name: GF_INSTALL_PLUGINS
        value: "grafana-piechart-panel"
    ingress:
      enabled: true
      host: ${GRAFANA_HOST}
      path: /grafana
      tls: true
    persistence:
      enabled: true
      storageClass: ${STORAGE_CLASS:-standard}
      size: ${GRAFANA_STORAGE_SIZE:-1Gi}
      
  prometheus:
    replicas: 1
    image: prom/prometheus:latest
    ingress:
      enabled: true
      host: ${PROMETHEUS_HOST}
      path: /prometheus
      tls: true
    persistence:
      enabled: true
      storageClass: ${STORAGE_CLASS:-standard}
      size: ${PROMETHEUS_STORAGE_SIZE:-5Gi}

# Secret configurations
secrets:
  postgres-credentials:
    - name: password
      value: ${POSTGRES_PASSWORD}
      
  redmica-secrets:
    - name: secret-key-base
      value: ${REDMINE_SECRET_KEY_BASE}
      
  ldap-credentials:
    - name: admin-password
      value: ${LDAP_ADMIN_PASSWORD}
    - name: config-password
      value: ${LDAP_CONFIG_PASSWORD}
      
  grafana-credentials:
    - name: admin-password
      value: ${GF_ADMIN_PASSWORD}
